dataset_csv: data/processed/preprocessed_words_400_papers.csv
dataset_name: words-400-manuscripts
outcome_colname: new_seq_data
ml_methods:
 - glmnet
 - rf
kfold: 5
ncores: 8
nseeds: 10
find_feature_importance: true
hyperparams: