dataset_csv: data/processed/data_avail_words_193_sequencing_papers.csv
dataset_name: data_avail_glmnet
outcome_colname: data_avail
ml_methods:
 - glmnet
kfold: 5
ncores: 4
nseeds: 10
find_feature_importance: true
