dataset_csv: data/processed/preprocessed_words_400_papers.csv
dataset_name: 400_papers_glmnet
outcome_colname: new_seq_data
ml_methods:
 - glmnet
kfold: 5
ncores: 4
nseeds: 10
find_feature_importance: true
